### ISSUE TITLE
We are not able to find mx parser classes in the updated version but was working in SRU2021-9.2.3

### ISSUE THREAD

**Issue by SVora-Fintech** [prowide/prowide-iso20022#104]
We are looking for SRU2023 datetime path changes, so need to upgrade the version as we need to parse files though "seev.031.002.13".
Changes suggested in path is like /Document/CorpActnNtfctn/CorpActnDtls/DtDtls/FctvDt/Dt for message type CANO
/Document/CorpActnNtfctn/CorpActnDtls/DtDtls/LtryDt/Dt and lot many more.

For this which version we can use for implementing above changes?
as currently we are using below implementation through gradle
implementation group: 'com.prowidesoftware', name: 'pw-iso20022', version: 'SRU2021-9.2.3'.

**Comment by zubri** [comment]
seev.031.002.13 was introduced in the SRU2023 thus you have it available in any version above 9.4.x

https://dev.prowidesoftware.com/SRU2023-10/release-notes/changelog-iso20022/
