### ISSUE TITLE
XmlNode/XmlParser missing?

### ISSUE THREAD

**Issue by v3rm0n** [prowide/prowide-iso20022#111]
The documentation references XmlNode and XmlParser for ISO20022 messages https://dev.prowidesoftware.com/latest/open-source/iso20022/iso20022-parser/ but I am not able to find them...

**Comment by zubri** [comment]
Yes, that's a mistake. `XmlNode` is part of the **Prowide Integrator** libraries.
The equivalent in the open source is the `MxNode`.
We will update the documentation accordingly.
