### ISSUE TITLE
Create pdu data 

### ISSUE THREAD

**Issue by mo3tasem74** [prowide/prowide-iso20022#116]
Dear Mr Zubri 
i have created an mx message but i am having difficulty creating the external part, which is DataPDU and header tag. like i can create from <apphdr> tag and below, i mean the body tag but for the above part, i don't know which class i should include to take an object from it and create the rest of the message as i did in the remaining part

this is my missing part 

?xml version="1.0"?> 
<ns:DataPDU 
       xmlns:ns="urn:swift:saa:xsd:saa.2.0"> 
     <ns:Header> 
       <ns:Message> 
          <ns:SenderReference>MXWebM522237</ns:SenderReference> 
          <ns:MessageIdentifier>camt.029.001.01</ns:MessageIdentifier> 
          <ns:Format>AnyXML</ns:Format> 
          <ns:SubFormat>Input</ns:SubFormat> 
          <ns:Sender> 
            <ns:DN>o=ptsausaa,o=swift</ns:DN> 
            <ns:FullName> 
               <ns:X1>PTSAUSAAXXX</ns:X1> 
            </ns:FullName> 
       </ns:Sender> 
       <ns:Receiver> 
         <ns:DN>o=ptsausaa,o=swift</ns:DN> 
         <ns:FullName> 
               <ns:X1>PTSAUSAAXXX</ns:X1> 
         </ns:FullName> 
       </ns:Receiver> 
       <ns:InterfaceInfo> 
         <ns:UserReference>MXWebM522237</ns:UserReference> 
       </ns:InterfaceInfo> 
       <ns:NetworkInfo> 
         <ns:IsNotificationRequested>true</ns:IsNotificationRequested> 
         <ns:Service>swift.generic.ia!x</ns:Service> 
       </ns:NetworkInfo> 
     </ns:Message> 
   </ns:Header>

**Comment by zubri** [comment]
Prowide has full support to build and parse the DataPDU wrapper in the **Prowide Integrator**. 
However such feature is not available in the open source library.

You could explore the Prowide Integrator offer. 

https://www.prowidesoftware.com/development-tools/integrator

Or if you want to handle that yourself, the way I would recommend is that you take the XSD schema for the DataPDU (this come from SWIFT Alliance Access, and there are multiple versions of it) and that you generate the model with **jaxb**. 

Then you would be able to marshall the wrapper in a similar way to what the ISO library does with the MX payloads.

Notice you can combine your own marshaller for the wrapper, and use the library serializer to inject afterwards the MX payload in the DataPDU Body element.
