### ISSUE TITLE
Cant parse ClrSysMmbId from AppHeader

### ISSUE THREAD

**Issue by heliosnarcissus** [prowide/prowide-iso20022#12]
Hi im trying to parse pacs008 and pacs009 using your library

When I try to parse a pacs008/pacs009 file appheader which contains this:
< FinInstnId >
     < ClrSysMmbId >
           < MmbId > ABCDEFGH < /MmbId >
        < /ClrSysMmbId >
< /FinInstnId >

the parser returns NULL for "From" and "To" elements in the AppHdr.

But when < FinInstnId > uses "BICFI" , everything is well.

So how do I properly use your library to parse "< ClrSysMmbId >" under AppHdr?

**Comment by zubri** [comment]
The AppHdr is just an interface, with convenient generic methods for common use cases. To access all the information in the parsed header you have to cast that to the specific header implementation.

Check this example:
https://github.com/prowide/prowide-iso20022-examples/blob/main/src/main/java/com/prowidesoftware/swift/samples/MxParseMessageWithHeader2.java
