### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by guiramos** [prowide/prowide-iso20022#126]
How can I build this project?

Intellij can't even build the gradle model because I could not go around this error:

```
Could not read 'https://api.adoptium.net/v3/binary/latest/8/ga/mac/aarch64/jdk/hotspot/normal/eclipse' as it does not exist.
```

**Comment by zubri** [comment]
You need a working Java 8, or Java 11 in the environment (depending if you are building version 9.x.x or 10.x.x of the library).

Then you just run ./gradlew build

For IntelliJ you can make it load the gradle configuration and to use the project gradle wrapper for building

**Comment by guiramos** [comment]
Thanks! I was able to add the maven dependency.
