### ISSUE TITLE
Support needed for camt.105.001.02 & camt.106.001.02 ISO20022 message types

### ISSUE THREAD

**Issue by amanisimpson7gss** [prowide/prowide-iso20022#128]
Hi,

On our platform, we have implemented support for the following 2 message types:
- camt.105.001.**02**
- camt.106.001.**02**

...However this library does not provide the mx models for the above 2 message types, so we are struggling to implement testing in our test-framework.

Please can the team add support for camt.105.001.**02** & camt.106.001.**02** ISO20022 message types.

Thanks,
Amani Simpson

**Comment by zubri** [comment]
Hi,

Those message types are part of the SRU2024 that we will make available for the general public soon.

**Comment by amanisimpson7gss** [comment]
Thanks @zubri for your reply.

Please could you advise on a rough estimated date-time of arrival for SRU2024.

Thanks,
Amani

**Comment by muhammadfarras** [comment]
> Thanks @zubri for your reply.
> 
> Please could you advise on a rough estimated date-time of arrival for SRU2024.
> 
> Thanks, Amani

Probaly it will release one month before november changes. It must be this month

**Comment by zubri** [comment]
Closing the issue. SRU2024 libraries were released already some weeks ago.
