### ISSUE TITLE
JSON Serialization / Deserialization errors of XMLGregorianCalendar backed date fields of MX objects

### ISSUE THREAD

**Issue by elominp** [prowide/prowide-iso20022#18]
Hello,

I have an issue when manipulating MX serialized as JSON files with various versions of JVMs (tested with Hotspot OpenJDK 1.8, 14 and 15).

Let's take for example a minimalist MX example with just a date (not valid as such, but it's to illustrate the problem which occurs with every date fields):

```
<?xml version="1.0" encoding="UTF-8" ?>
<RequestPayload>
<Doc:Document xmlns:Doc="urn:swift:xsd:sese.023.002.01">
    <Doc:SctiesSttlmTxInstr>
        <Doc:Id>
            <Doc:CreDtTm>
                <Doc:Dt>2021-02-03</Doc:Dt>
            </Doc:CreDtTm>
        </Doc:Id>
    </Doc:SctiesSttlmTxInstr>
</Doc:Document>
</RequestPayload>
```

When I parse and convert this to a JSON output doing a simple `AbstractMX.parse(source).toJson()`, here is the output I obtain:

```
{
  "sctiesSttlmTxInstr": {
    "id": {
      "creDtTm": {
        "dt": {
          "year": 2021,
          "month": 2,
          "day": 3,
          "timezone": -2147483648,
          "hour": -2147483648,
          "minute": -2147483648,
          "second": -2147483648
        }
      }
    }
  },
  "type": "MX",
  "@xmlns": "urn:swift:xsd:sese.023.002.01",
  "identifier": "sese.023.002.01"
}
```

It serializes the XMLGregorianCalendar instance as complex object with every attributes mentionned, with some other libraries I get instead a string (for example `2021-02-03`) but anyway, here's the real problem:

If I want to load again the MX from its JSON serialization, the dates fields throw a `NullPointerException` on line 68 of `XMLGregorianCalendarAdapter.java` file: https://github.com/prowide/prowide-iso20022/blob/0181a8a017f7bf11bf9fc6d2de261265b67f3402/iso20022-core/src/main/java/com/prowidesoftware/swift/model/mx/XMLGregorianCalendarAdapter.java#L68

Because the return value in this case of `obj.get(FRACTIONAL)` is `null`

Because of this error, dates are lost and the corresponding fields are `null` objects in the parsed AbstractMX instance, thus if I reserialize this object I get the following output:

```
{
  "sctiesSttlmTxInstr": {
    "id": {
      "creDtTm": {}
    }
  },
  "type": "MX",
  "@xmlns": "urn:swift:xsd:sese.023.002.01",
  "identifier": "sese.023.002.01"
}
```

However, if I tweak the generated JSON to add the `fractionalSecond` field manually, the following test pass correctly and the dates are correctly deserialized / serialized:

```
    @Test
    public void testCustomJson()
    {
        String source = """
{
  "sctiesSttlmTxInstr": {
    "id": {
      "creDtTm": {
        "dt": {
          "year": 2021,
          "month": 2,
          "day": 3,
          "timezone": -2147483648,
          "hour": -2147483648,
          "minute": -2147483648,
          "second": -2147483648,
          "fractionalSecond": 0
        }
      }
    }
  },
  "type": "MX",
  "@xmlns": "urn:swift:xsd:sese.023.002.01",
  "identifier": "sese.023.002.01"
}""";
        AbstractMX mx = AbstractMX.fromJson(source);
        assertEquals(source, mx.toJson());
    }
```

What I expect is the following test to pass:

```
    @Test
    public void testMxDateJsonSerializeAndParse()
    {
        String source = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" +
                "<RequestPayload>\n" +
                "<Doc:Document xmlns:Doc=\"urn:swift:xsd:sese.023.002.01\">\n" +
                "    <Doc:SctiesSttlmTxInstr>\n" +
                "        <Doc:Id>\n" +
                "            <Doc:CreDtTm>\n" +
                "                <Doc:Dt>2021-02-03</Doc:Dt>\n" +
                "            </Doc:CreDtTm>\n" +
                "        </Doc:Id>\n" +
                "    </Doc:SctiesSttlmTxInstr>\n" +
                "</Doc:Document>\n" +
                "</RequestPayload>";
        AbstractMX mx = AbstractMX.parse(source);
        String json = mx.toJson();
        AbstractMX mx2 = AbstractMX.fromJson(json);
        String json2 = mx2.toJson();
        assertEquals(mx, mx2);
        assertEquals(json, json2);
    }
```

Technical fix of this issue is quite easy, I'm preparing a PR with an example of fix but it's more a matter of the default functional value you want in the serialized JSON for the `fractionalSecond` field (not present like currently, present with a default `0` or any other form of decimal `0` value)

**Comment by alexandergorokhov** [comment]
Change was accepted. Thank you elominp.
