### ISSUE TITLE
fromJson fails  AbstractMXAdapter

### ISSUE THREAD

**Issue by zubri** [prowide/prowide-iso20022#26]
El fromJson falla cuando el JSON tiene un appHdr, porque no puede resolver la interface:

Unable to invoke no-args constructor for interface com.prowidesoftware.swift.model.mx.AppHdr. Registering an InstanceCreator with Gson for this type may fix this problem.

El adapter esta en AbstractMXAdapter

Hay que detectar el tipo de header y usar la class correspondiente. Tal vez sea necesario al serializar guardar el header type, para lo cual se puede usr el enum AppHdrType

Ver failing test en AbstractMxJsonTest#testMessageWithAppHdr.   branch issue/3

**Comment by Alban42** [comment]
We have the same problem using an appHdr.

Any idea when this issue will be resolved ?

Thanks !

**Comment by elominp** [comment]
I opened a PR (#27 ) with a gist of code I had to workaround this issue during some of our tests if it can help.

Same question as @Alban42 , do you have any idea when this issue will be resolved? It kind of delays currently our developments manipulating the apphdr when the source is a Json object (main serialization format we're using)

**Comment by zubri** [comment]
Great. Thanks for the PR @elominp 
Will review and merge into a release asap.

**Comment by zubri** [comment]
This is merged, the release 9.1.7 will be out soon.

Instead of the class name, we have added the header namespace as JSON field, which is a bit more business oriented. So that the JSON is not coupled with an implementation class that eventually could change.

**Comment by elominp** [comment]
Thank you very much for the reactivity 👍
