### ISSUE TITLE
Security issue was fixed in Gson version: 2.8.9 

### ISSUE THREAD

**Issue by luongnvUIT** [prowide/prowide-iso20022#37]
Security issue was fixed in Gson version: 2.8.9 
Ref: https://github.com/google/gson/pull/1991
Please help to update to that version for gson library.

**Comment by luongnvUIT** [comment]
Thanks for your help, @zubri . When is this change released? If it is good to go, I could upgrade the version on my side.

**Comment by zubri** [comment]
We are about to do a release with this change.
