### ISSUE TITLE
JSON serialization of datetime fields for iso20022 messages results in multiple parts?

### ISSUE THREAD

**Issue by seanleblancicdtech** [prowide/prowide-iso20022#40]
Is there a way to customize this to produce an ISO 8601 format?

For example, the output I get when serializing to JSON (with toJson() on the AbstractMX class) for creDtTm:

"creDtTm": {
        "year": 2022,
        "month": 1,
        "day": 14,
        "timezone": 0,
        "hour": 13,
        "minute": 44,
        "second": 39,
        "fractionalSecond": 0.319
      }

**Comment by zubri** [comment]
Yes, there is a custom adapter to do that on purpose. 

Check the answer in https://github.com/prowide/prowide-iso20022/issues/42

You could create your own JSON serialization method without the adapter.
