### ISSUE TITLE
JSON serialization to lowercase names?

### ISSUE THREAD

**Issue by seanleblancicdtech** [prowide/prowide-iso20022#42]
Is there a way to coerce these to use uppercase names?

For example, at the top level of a setr.010.001.04 message, instead of getting  something like 

`{
    "SbcptOrdr": {...`

we get this:

`{
     "sbcptOrdr": {...`

and so on for every key in the JSON output when calling .toJson().

**Comment by zubri** [comment]
The provided `toJson` is one of many options to serialize the model as JSON. It is intended to be used in combination of the `fromJson` that does the opposite conversion.

Said that, this default implementation is currently a conversion using GSON default naming strategy as you can see here:
https://github.com/prowide/prowide-iso20022/blob/1c93ab4427a5f0834d11550e368ec91a65fec112/iso20022-core/src/main/java/com/prowidesoftware/swift/model/mx/AbstractMX.java#L575

For your use case, you could add a similar method within your application and set to the Gson builder another strategy, such as:

`builder.setFieldNamingPolicy(UPER_CAMEL_CASE)`

that I understand would produce what you expect.
