### ISSUE TITLE
Non-static getters for static fields on children of com.prowidesoftware.swift.model.mx.AbstractMX

### ISSUE THREAD

**Issue by vhortal** [prowide/prowide-iso20022#53]
Taking as example the class `com.prowidesoftware.swift.model.mx.MxPacs00800108`, I see getters like
`public int getFunctionality()`
`public int getVariant()`
`public int getVersion()`
among others. These refer to static fields, so in my view the getters should also be declared static.

I have faced problems while trying to serialize instances of these classes as JSON with Jackson, because the non-static getters make the static fields appear as properties, so they get serialized into the JSON object, hence including elements such as `"functionality"`, `"variant"`, `"version"` that do not belong to the model.

The issue seems to affect most of the inheritors of AbstractMX, possibly also present in other packages.

**Comment by ptorres-prowide** [comment]
Hello vhortal, in case you need to serialize any of those instances you can use this approach:

        MxPacs00800108 msg = ...
        String jsonMsg = msg.toJson();
