### ISSUE TITLE
Error in Parsing admi.004.001.01

### ISSUE THREAD

**Issue by graghsaka** [prowide/prowide-iso20022#55]
In admi.001.001.01 there's a xml tag "SysEvtNtfnV01", but theres no suppor for this in the library. I could only found SystemEventNotificatioV02 class not V01 class. Is there are any other way to parse <SysEvtNtfnV01> tag.

**Comment by ptorres-prowide** [comment]
Hello graghsaka, could you share an example of the msg that you're trying to parse?
Thank you
Regards
