### ISSUE TITLE
Review usage of the XMLGregorianCalendarAdapter in java above 8

### ISSUE THREAD

**Issue by zubri** [prowide/prowide-iso20022#60]
https://stackoverflow.com/questions/71489410/prowide-library-exception-while-processing-iso-20022-messages-with-dates/71506567?noredirect=1#comment129756874_71506567

We do have a custom Json serializer for the XMLGregorianCalendar and we configure it in the Gson calls. However, according to the post, Gson is not picking it up in the toJson serialization.

**Comment by ptorres-prowide** [comment]
You´ll need to add the following deps in order to build the project under Java 11:

implementation 'javax.xml.bind:jaxb-api:2.3.1'
implementation 'com.sun.xml.bind:jaxb-impl:2.3.3'

Regards
