### ISSUE TITLE
caaa version upgrade

### ISSUE THREAD

**Issue by gverran** [prowide/prowide-iso20022#63]
Using 9.2.8, caaa 001, 002, 003, etc only has up to version 8 whereby v11 is already available.  Can you please update to include the later versions of all caaa messages?

**Comment by zubri** [comment]
We are trying to get the enriched schemas we need for this missing model classes

**Comment by gverran** [comment]
Where would you obtain this from?  I guess this is in addition to the XSDs on iso20022.org?

**Comment by zubri** [comment]
From swift since we are a registered provider (we use the enriched schemas for internal code generation in other libraries). 
If we cannot make it to get the enriched schemas we will generate the code for the open source with the ISO xsds.

**Comment by gverran** [comment]
Thanks, how long do you wait from Swift that would cause you to use the ISO xsds instead?

**Comment by zubri** [comment]
Added in release SRU2022-9.3.4
