### ISSUE TITLE
Parsing issue with MX message of type seev.031.002.09

### ISSUE THREAD

**Issue by CBhavsar-Fintech** [prowide/prowide-iso20022#8]
Hi-
We are working to parse swift mx message of type seev.031.002.09
But, when we try to parse message using class MxSeev03100209 or AbstractMX or XMLParser parse method
we are getting exception and not able to parse xml data.
Attached is a file containing xml data we are working to parse.

Could you please assist on how to we can parse given xml data if possible could you send sample?
[ABC_CANO.CA.ID.111111111.txt](https://github.com/prowide/prowide-iso20022/files/5634303/ABC_CANO.CA.ID.111111111.txt)

**Comment by lgargioni** [comment]
Hi, how did you use the class MxSeev03100209? 
I try to search the seev classes in `import com.prowidesoftware.swift.model.mx.` , but I didn't find anything.
Thank you

**Comment by CBhavsar-Fintech** [comment]
I use seev clases from https://github.com/prowide/prowide-iso20022/tree/develop/model-seev-mx/src/generated/java/com/prowidesoftware/swift/model/mx

**Comment by zubri** [comment]
> Hi-
> We are working to parse swift mx message of type seev.031.002.09
> But, when we try to parse message using class MxSeev03100209 or AbstractMX or XMLParser parse method
> we are getting exception and not able to parse xml data.
> Attached is a file containing xml data we are working to parse.
> 
> Could you please assist on how to we can parse given xml data if possible could you send sample?
> [ABC_CANO.CA.ID.111111111.txt](https://github.com/prowide/prowide-iso20022/files/5634303/ABC_CANO.CA.ID.111111111.txt)

@CBhavsar-Fintech 

The issue is caused by the SplmtryData element. If you remove that from the message content, the parser works just fine.

The root cause is the ISO namespace within that supplementary data, it breaks our filter implementation.
I've created a test case for it so we can debug it for a workaround or fix.

----

> Hi, how did you use the class MxSeev03100209?
> I try to search the seev classes in `import com.prowidesoftware.swift.model.mx.` , but I didn't find anything.
> Thank you

@lgargioni 

If you use the Fat jar in the Maven/Gradle distribution you have all model classes in a single dependency. See the README for details on the jar files structure.

**Comment by CBhavsar-Fintech** [comment]
Thanks for the update. Looking forward to the workaround or fix.

**Comment by JVaghela-Fintech** [comment]
When we can expect the release?

**Comment by zubri** [comment]
The fix is already in the develop branch if you want to build the jar. 
We will make a public release with this soon though, this week hopesfully.

**Comment by zubri** [comment]
The release is ready at GitHub
https://github.com/prowide/prowide-iso20022/releases/tag/SRU2020-9.1.5

Will be available in Maven soon

**Comment by JVaghela-Fintech** [comment]
Many thanks

**Comment by hamri** [comment]
Hello,

We are facing a similar problem while parsing an MX message of type admi.007.001.01. We are using SRU2020-9.1.5 version and upgrading to SRU2021-9.2.5 version doesn't resolve the issue.

This is an example of admi.007.001.01 message :

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<Body>
    <AppHdr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.01">
        <Fr>
            <FIId>
                <FinInstnId>
                    <BICFI>XXXXXXXXXXX</BICFI>
                </FinInstnId>
            </FIId>
        </Fr>
        <To>
            <FIId>
                <FinInstnId>
                    <BICFI>XXXXXXXXXXX</BICFI>
                </FinInstnId>
            </FIId>
        </To>
        <BizMsgIdr>XXXXXXX</BizMsgIdr>
        <MsgDefIdr>admi.007.001.01</MsgDefIdr>
        <CreDt>2022-01-11T15:02:09Z</CreDt>
    </AppHdr>
    <Document xmlns="urn:iso:std:iso:20022:tech:xsd:admi.007.001.01">
        <RctAck>
            <MsgId>
                <MsgId>XXXXXXX</MsgId>
            </MsgId>
            <Rpt>
                <RltdRef>
                    <Ref>XXXXXX</Ref>
                </RltdRef>
                <ReqHdlg>
                    <StsCd>ACKT</StsCd>
                    <Desc>CR50</Desc>
                </ReqHdlg>
            </Rpt>
            <SplmtryData>
                <Envlp>
                    <FromBOData>TOTO</FromBOData>
                </Envlp>
            </SplmtryData>
        </RctAck>
    </Document>
</Body>
```

Could you please help us to fix the parsing?

Best regards,
