### ISSUE TITLE
Date and time formats in ISO-20022 JSON

### ISSUE THREAD

**Issue by gverran** [prowide/prowide-iso20022#94]
Is there a reason why the date and times are represented in JSON in different fields instead of using the OpenAPI date time format?
eg:  yyyy-MM-ddTHH:mm:ss+zz:zz

eg:  2023-07-12T15:22:53+00:00

**Comment by zubri** [comment]
It was reasonable at the time, to be consistent with the JSON structures we used to have MT messages, where we split everything that can be parsed. Also to have more control over the marshalling/unmarshalling date for the legacy `XMLGregorianCalendar` objects.

With the new `java.time` implementations used in release 10, we explored several options. Including using default string representation for the different `java.time` objects, but non was good enough for consistency. So we ended up adding adapters for it. 

You can check here the current representation for all date and date time elements depending on the model type.

https://dev.prowidesoftware.com/SRU2023-10/open-source/iso20022/iso20022-mx-json/#date-and-time-formats
